kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubewise.serviceAccountName" . }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "get", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubewise.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubewise.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kubewise.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
