apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubewise.fullname" . }}
  labels:
    {{- include "kubewise.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubewise.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubewise.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "kubewise.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KW_HANDLER
              value: "{{ .Values.handler }}"
            - name: KW_SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kubewise
                  key: kw_slack_token
            - name: KW_SLACK_CHANNEL
              value: "{{ .Values.slack.channel }}"
            - name: KW_GOOGLECHAT_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: kubewise
                  key: kw_googlechat_webhook_url
            - name: KW_NAMESPACE
              value: "{{ .Values.namespaceToWatch }}"
            - name: KW_MESSAGE_PREFIX
              value: "{{ .Values.messagePrefix }}"
