{{- if and .Values.rbac.create (eq .Values.clusterRole.create false) -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubewise.serviceAccountName" . }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "get", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubewise.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubewise.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: {{ include "kubewise.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
