apiVersion: v1
kind: Secret
metadata:
  name: kubewise
type: Opaque
stringData:
  kw_slack_token: "{{ .Values.slack.token }}"
  kw_googlechat_webhook_url: "{{ .Values.googlechat.webhookUrl }}"
  kw_webhook_auth_token: "{{ .Values.webhook.authToken }}"